version: '3.8'

services:
  app:
    build: .
    container_name: app_container
    ports:
      - "3000:3000"   # Expone el puerto 3000 para acceder a la app en el navegador
    depends_on:
      - mongo          # Garantiza que el contenedor de MongoDB se inicie primero
    environment:
      - DB_HOST=mongo  # Nombre del contenedor de MongoDB
      - DB_PORT=27017  # Puerto predeterminado de MongoDB
      - DB_NAME=Login  # Nombre de la base de datos 'Login'
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"  # Exponer el puerto de MongoDB
    volumes:
      - mongo-data:/data/db  # Volumen persistente para MongoDB
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
